from typing import Dict, NamedTuple, Set, Optional, List


class BFMLocationData(NamedTuple):
    region: str
    location_group: Optional[str] = None


location_base_id = 0x06dc40

location_table: Dict[str, BFMLocationData] = {
    "Guard Bincho - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Bincho"),
    "Seer Bincho - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Bincho"),
    "Hawker Bincho - Somnolent Forest Deadend": BFMLocationData("Somnolent Forest Deadend",location_group = "Bincho"),
    "Maid Bincho - Somnolent Forest Behind Steam": BFMLocationData("Somnolent Forest Behind Steam",location_group = "Bincho"),
    "MusicianB Bincho - Steamwood Forest": BFMLocationData("Steamwood Forest",location_group = "Bincho"),
    "SoldierA Bincho - Twinpeak Entrance": BFMLocationData("Twinpeak Entrance",location_group = "Bincho"),
    "MercenC Bincho - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Bincho"),
    "CarpentA Bincho - Twinpeak Second Peak": BFMLocationData("Twinpeak Second Peak",location_group = "Bincho"),
    "KnightB Bincho - Twinpeak Second Peak": BFMLocationData("Twinpeak Second Peak",location_group = "Bincho"),
    "Shepherd Bincho - Twinpeak Rope Bridge": BFMLocationData("Twinpeak Rope Bridge",location_group = "Bincho"),
    "Baliff Bincho - Restaurant Basement Behind Pole Jumps": BFMLocationData("Restaurant Basement Behind Pole Jumps",location_group = "Bincho"),
    "Taster Bincho - Restaurant Basement Path to Crest Guardian": BFMLocationData("Restaurant Basement Path to Crest Guardian",location_group = "Bincho"),
    "CarpentB Bincho - Restaurant Basement Dark Platform Maze 2": BFMLocationData("Restaurant Basement Dark Platform Maze 2",location_group = "Bincho"),
    "Weaver Bincho - Twinpeak Second Peak": BFMLocationData("Twinpeak Second Peak",location_group = "Bincho"),
    "SoldierB Bincho - Restaurant Basement Planks Over Lava": BFMLocationData("Restaurant Basement Planks Over Lava",location_group = "Bincho"),
    "KnightA Bincho - Mine Conveyor Belt Room": BFMLocationData("Mine Conveyor Belt Room",location_group = "Bincho"),
    "CookA Bincho - Misteria Underground Lake": BFMLocationData("Misteria Underground Lake",location_group = "Bincho"),
    "Acrobat Bincho - Steamwood Forest": BFMLocationData("Steamwood Forest",location_group = "Bincho"),
    "MercenB Bincho - Restaurant Basement Bowling 2": BFMLocationData("Restaurant Basement Bowling 2",location_group = "Bincho"),
    "Janitor Bincho - Frozen Palace Blue Eye Door": BFMLocationData("Frozen Palace Blue Eye Door",location_group = "Bincho"),
    "Artisan Bincho - Island of Dragons": BFMLocationData("Island of Dragons",location_group = "Bincho"),
    "CarpentC Bincho - Mine Conveyor Belt Room": BFMLocationData("Mine Conveyor Belt Room",location_group = "Bincho"),
    "MusicianC Bincho - Frozen Palace Green Eye Maze": BFMLocationData("Frozen Palace Green Eye Maze",location_group = "Bincho"),
    "Knitter Bincho - Twinpeak Path to Skullpion": BFMLocationData("Twinpeak Path to Skullpion",location_group = "Bincho"),
    "Chef Bincho - Frozen Palace Crate Pile": BFMLocationData("Frozen Palace Crate Pile",location_group = "Bincho"),
    "MercenA Bincho - Restaurant Basement Bowling 1": BFMLocationData("Restaurant Basement Bowling 1",location_group = "Bincho"),
    "Chief Bincho - Misteria Underground Lake": BFMLocationData("Misteria Underground Lake",location_group = "Bincho"),
    "CookB Bincho - Upper Mines": BFMLocationData("Upper Mines Behind Posion",location_group = "Bincho"),
    "Conductor Bincho - Upper Mines Ant Parade": BFMLocationData("Upper Mines Ant Parade",location_group = "Bincho"),
    "Butcher Bincho - Frozen Palace Atrium Right Balcony": BFMLocationData("Frozen Palace Atrium Right Balcony",location_group = "Bincho"),
    "KnightC Bincho - Restaurant Basement Dark Platform Maze 3": BFMLocationData("Restaurant Basement Dark Platform Maze 3",location_group = "Bincho"),
    "Doctor Bincho - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Bincho"),
    "KnightD Bincho - Upper Mines Before Digging": BFMLocationData("Upper Mines Before Digging",location_group = "Bincho"),
    "Alchemist Bincho - Frozen Palace Red Eye Maze": BFMLocationData("Frozen Palace Red Eye Maze",location_group = "Bincho"),
    "Librarian Bincho - Restaurant Basement Near Rotating Platforms": BFMLocationData("Restaurant Basement Near Rotating Platforms",location_group = "Bincho"),
    "Minku - Grillin Village Near Twinpeak": BFMLocationData("Upper Grillin Village",location_group = "Minku"),
    "Minku - Somnolent Forest Hidden Path": BFMLocationData("Somnolent Forest",location_group = "Minku"),
    "Minku - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Minku"), 
    "Minku - Grillin Village Above Gondola": BFMLocationData("Upper Grillin Village",location_group = "Minku"),
    "Minku - Skullpion Arena": BFMLocationData("Skullpion Arena",location_group = "Minku"),
    "Minku - Steamwood Forest": BFMLocationData("Steamwood Forest",location_group = "Minku"),
    "Minku - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Minku"),
    "Minku - Twinpeak End of Stream": BFMLocationData("Twinpeak Around the Bend",location_group = "Minku"),
    "Minku - Misteria Underground Lake": BFMLocationData("Misteria Underground Lake",location_group = "Minku"),
    "Minku - Grillin Reservoir": BFMLocationData("Grillin Reservoir",location_group = "Minku"),
    "Minku - Upper Mines Below Big Fan": BFMLocationData("Upper Mines Big Fan Room",location_group = "Minku"),
    "Minku - Upper Mines": BFMLocationData("Upper Mines",location_group = "Minku"),
    "Minku - Near Wind Scroll": BFMLocationData("Wind Scroll",location_group = "Minku"),
    "500 Drans Chest - Somnolent Forest Behind Steam": BFMLocationData("Somnolent Forest Behind Steam"),
    "Old Crown Chest - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Chest"),
    "Aged Coin Chest - Steamwood Forest": BFMLocationData("Steamwood Forest",location_group = "Chest"),
    "200 Drans Chest - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Chest"),
    "Old Book Chest - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Chest"),
    "Rock Chest - Twinpeak Second Peak": BFMLocationData("Twinpeak Second Peak",location_group = "Chest"),
    "Dagger Chest - Twinpeak Rope Bridge": BFMLocationData("Twinpeak Rope Bridge",location_group = "Chest"),
    "Bracelet Chest - Twinpeak Entrance": BFMLocationData("Twinpeak Entrance",location_group = "Chest"),
    "200 Drans Chest - Twinpeak Path to Skullpion": BFMLocationData("Twinpeak Path to Skullpion",location_group = "Chest"),
    "Red Eye Chest - Frozen Palace Red Eye Room": BFMLocationData("Frozen Palace Red Eye Room",location_group = "Chest"),
    "Blue Eye Chest - Frozen Palace Red Eye Maze": BFMLocationData("Frozen Palace Red Eye Maze",location_group = "Chest"),
    "Green Eye Chest - Frozen Palace Green Eye Maze": BFMLocationData("Frozen Palace Green Eye Maze",location_group = "Chest"),
    "Red Shoes Chest - Frozen Palace Atrium Left Balcony": BFMLocationData("Frozen Palace Atrium Left Balcony",location_group = "Chest"),
    "Long Tube Chest - Frozen Palace Red Eye Door": BFMLocationData("Frozen Palace Red Eye Door",location_group = "Chest"),
    "500 Drans Chest - Island of Dragons": BFMLocationData("Island of Dragons",location_group = "Chest"),
    "Shield Chest - Restaurant Basement Bowling 1": BFMLocationData("Restaurant Basement Bowling 1",location_group = "Chest"),
    "Odd Hat Chest - Restaurant Basement Bowling 1": BFMLocationData("Restaurant Basement Bowling 1",location_group = "Chest"),
    "Old Sword Chest - Restaurant Basement": BFMLocationData("Restaurant Basement",location_group = "Chest"),
    "Old Shirt Chest - Grillin Reservoir": BFMLocationData("Grillin Reservoir",location_group = "Chest"),
    "300 Drans Chest - Restaurant Basement": BFMLocationData("Restaurant Basement",location_group = "Chest"),
    "Old Pipe Chest - Restaurant Basement Planks Over Lava": BFMLocationData("Restaurant Basement Planks Over Lava",location_group = "Chest"),
    "Powder Chest - Restaurant Basement Teleport Maze": BFMLocationData("Restaurant Basement Teleport Maze",location_group = "Chest"),
    "Helmet Chest - Restaurant Basement Dark Platform Maze 3": BFMLocationData("Restaurant Basement Dark Platform Maze 3",location_group = "Chest"),
    "Old Glove Chest - Misteria Underground Lake": BFMLocationData("Misteria Underground Lake",location_group = "Chest"),
    "Cloth Chest - Restaurant Basement": BFMLocationData("Restaurant Basement",location_group = "Chest"),
    "Used Boot Chest - Grillin Reservoir": BFMLocationData("Grillin Reservoir",location_group = "Chest"),
    "White Cloth Chest - Frozen Palace Green Eye Maze": BFMLocationData("Frozen Palace Green Eye Maze",location_group = "Chest"),
    "Red Cloth Chest - Frozen Palace Green Eye Maze": BFMLocationData("Frozen Palace Green Eye Maze",location_group = "Chest"),
    "Black Cloth Chest - Frost Dragon Door": BFMLocationData("Frost Dragon Door",location_group = "Chest"),
    "Glasses Chest - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Chest"),
    "Large Tool Chest - Upper Mines": BFMLocationData("Upper Mines Behind Posion",location_group = "Chest"),
    "Odd Bone Chest - Upper Mines": BFMLocationData("Upper Mines Behind Posion",location_group = "Chest"),
    "Armor Chest - Reservoir Tunnel": BFMLocationData("Reservoir Tunnel",location_group = "Chest"),
    "Lumina - Spiral Tower": BFMLocationData("Spiral Tower",location_group = "Equipment"),
    "Item 1 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery"),
    "Item 2 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery"),
    "Item 3 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery"),
    "Item 4 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery"),
    "Item 5 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery"),
    "Item 6 (JamBread) - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery"),
    "Item 7 (Biscuit) - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery"),
    "Item 1 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant"),
    "Item 2 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant"),
    "Item 3 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant"),
    "Item 4 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant"),
    "Item 5 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant"),
    "Item 6 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant"),
    "Item 7 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant"),
    "Item 1 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 2 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 3 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 4 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 5 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 6 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 7 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 8 (Orange) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 9 (EX-Drink) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 10 (H-Mint) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 11 (Riceball) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Item 12 (Neat Ball) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery"),
    "Musashi - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop"),
    "Bee Plant - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop"),
    "Soldier1 - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop"),
    "Soldier2 - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop"),
    "Rootrick - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop"),
    "Steam Knight - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop"),
    "Soldier3 - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop"),
    "Herb Plant - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop"),
    "King Man Eater - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop"),
    "Magician - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop"),
    "Sleepie - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop"),
    "Skullpion - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop"),
    "Relic Vambee - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop"),
    "Vambee Soldier - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop"),
    "Bowler - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop"),
    "Cure Worm - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop"),
    "Bubbles - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop"),
    "Relic Keeper - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop"),
    "Penguin - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop"),
    "Haya Wolf - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop"),
    "Slow Guy - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop"),
    "Stomp Golem - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop"),
    "Gingerelle - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop"),
    "Frost Dragon - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop"),
    "GiAnt - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop"),
    "Toad Stool - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop"),
    "Ed & Ben - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop"),
    "Topo - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop"),
    "Colonel Capricola - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop"),
    "Queen Ant - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop"),
    "Improved Fusion (Artisan) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech"),
    "Dashing Pierce (Maid) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech"),
    "Shish Kebab (Clown) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech"),
    "Crosswise Cut (KnightB) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech"),
    "Tenderize (KnightA) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech"),
    "Desperado Attack (KnightC) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech"),
    "Rumparoni Special (KnightD) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech"),
    "Earth Scroll - Twinpeak First Peak": BFMLocationData("Twinpeak Around the Bend",location_group = "Scroll"),
    "Water Scroll - Grillin Reservoir": BFMLocationData("Grillin Reservoir",location_group = "Scroll"),
    "Fire Scroll - Island of Dragons": BFMLocationData("Island of Dragons",location_group = "Scroll"),
    "Wind Scroll - Grillin Volcano": BFMLocationData("Wind Scroll",location_group = "Scroll"),
    "Sky Scroll - Sky Island": BFMLocationData("Sky Island",location_group = "Scroll"),
    "Defeat Earth Crest Guardian - Skullpion Arena": BFMLocationData("Skullpion Arena",location_group = "Core"),
    "Defeat Water Crest Guardian - Relic Keeper Arena": BFMLocationData("Relic Keeper Arena",location_group = "Core"),
    "Defeat Fire Crest Guardian - Frost Dragon Arena": BFMLocationData("Frost Dragon Arena",location_group = "Core"),
    "Defeat Wind Crest Guardian - Queen Ant Arena": BFMLocationData("Queen Ant Arena",location_group = "Core"),
    "lvl 2 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 3 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 4 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 5 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 6 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 7 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 8 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 9 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 10 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 11 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 12 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 13 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 14 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 15 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 16 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 17 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 18 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 19 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 20 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 21 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 22 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 23 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 24 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 25 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 26 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 27 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 28 Body - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 29 Body - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 30 Body - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 2 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 3 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 4 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 5 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 6 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 7 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 8 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 9 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 10 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 11 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 12 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 13 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 14 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 15 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 16 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 17 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 18 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 19 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 20 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 21 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 22 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 23 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 24 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 25 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 26 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 27 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 28 Mind - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 29 Mind - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 30 Mind - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 2 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 3 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 4 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 5 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 6 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 7 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 8 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 9 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 10 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 11 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 12 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 13 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 14 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 15 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 16 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 17 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 18 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 19 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 20 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 21 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 22 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 23 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 24 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 25 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 26 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 27 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 28 Fus - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 29 Fus - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 30 Fus - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 2 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 3 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 4 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 5 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 6 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 7 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 8 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level"),
    "lvl 9 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 10 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 11 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 12 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 13 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 14 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 15 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 16 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level"),
    "lvl 17 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 18 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 19 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 20 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 21 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 22 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level"),
    "lvl 23 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 24 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 25 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 26 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 27 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level"),
    "lvl 28 Lum - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 29 Lum - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
    "lvl 30 Lum - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level"),
}

sphere_one: List[str] = [
    "Guard Bincho - Somnolent Forest",
    "Seer Bincho - Somnolent Forest",
    "Hawker Bincho - Somnolent Forest",
    "MusicianB Bincho - Steamwood Forest",
    "SoldierA Bincho - Twinpeak Entrance",
    "Acrobat Bincho - Steamwood Forest"
]

standard_location_name_to_id: Dict[str, int] = {name: location_base_id + index for index, name in enumerate(location_table)}

all_locations = location_table.copy()


location_name_groups: Dict[str, Set[str]] = {}
for loc_name, loc_data in location_table.items():
    loc_group_name = loc_name.split(" - ", 1)[1]
    location_name_groups.setdefault(loc_group_name, set()).add(loc_name)
    if loc_data.location_group:
        location_name_groups.setdefault(loc_data.location_group, set()).add(loc_name)


table_ids_to_hint: List[int] = []
for loc_name, loc_id in standard_location_name_to_id.items():
    if(location_table[loc_name].location_group):
        #if(not location_table[loc_name].location_group in ["Bakery", "Equipment", "Minku", "Restaurant", "Grocery", "Toy Shop", "Tech"]):
        if(location_table[loc_name].location_group in ["Bincho", "Chest"]):
            table_ids_to_hint.append(loc_id)
    else:
        table_ids_to_hint.append(loc_id)
