from typing import Dict, NamedTuple, Set, Optional, List


class BFMLocationData(NamedTuple):
    region: str
    location_group: Optional[str] = None
    jp_name: Optional[str] = None


location_base_id = 0x06dc40
jp_id_offset = 0x0c0000

location_table: Dict[str, BFMLocationData] = {
    "Guard Bincho - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Bincho", jp_name = "みはりのナミロスのビンチョ - すいまの森"),
    "Seer Bincho - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Bincho", jp_name = "うらないしギアラのビンチョ - すいまの森"),
    "Hawker Bincho - Somnolent Forest Deadend": BFMLocationData("Somnolent Forest Deadend",location_group = "Bincho", jp_name = "たかじょうトクセンのビンチョ - すいまの森"),
    "Maid Bincho - Somnolent Forest Behind Steam": BFMLocationData("Somnolent Forest Behind Steam",location_group = "Bincho", jp_name = "そうじふジョミーノのビンチョ - すいまの森"),
    "MusicianB Bincho - Steamwood Forest": BFMLocationData("Steamwood Forest",location_group = "Bincho", jp_name = "フーソッシモがくしのビンチョ - スチームウッドの森"),
    "SoldierA Bincho - Twinpeak Entrance": BFMLocationData("Twinpeak Entrance",location_group = "Bincho", jp_name = "ヘいしバラニックのビンチョ - ふたご山"),
    "MercenC Bincho - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Bincho", jp_name = "ようへいミーノのビンチョ - ふたご山"),
    "CarpentA Bincho - Twinpeak Second Peak": BFMLocationData("Twinpeak Second Peak",location_group = "Bincho", jp_name = "だいくツケコンデルのビンチョ - ふたご山"),
    "KnightB Bincho - Twinpeak Second Peak": BFMLocationData("Twinpeak Second Peak",location_group = "Bincho", jp_name = "きしラドのビンチョ - ふたご山"),
    "Shepherd Bincho - Twinpeak Rope Bridge": BFMLocationData("Twinpeak Rope Bridge",location_group = "Bincho", jp_name = "うまやばんバッサシのビンチョ - ふたご山"),
    "Baliff Bincho - Restaurant Basement Behind Pole Jumps": BFMLocationData("Restaurant Basement Behind Pole Jumps",location_group = "Bincho", jp_name = "グラムだいかんのビンチョ - バーの地下"),
    "Taster Bincho - Restaurant Basement Path to Crest Guardian": BFMLocationData("Restaurant Basement Path to Crest Guardian",location_group = "Bincho", jp_name = "9だいめどくみやくのビンチョ - バーの地下"),
    "CarpentB Bincho - Restaurant Basement Dark Platform Maze 2": BFMLocationData("Restaurant Basement Dark Platform Maze 2",location_group = "Bincho", jp_name = "だいくニコミテールのビンチョ - バーの地下"),
    "Weaver Bincho - Twinpeak Second Peak": BFMLocationData("Twinpeak Second Peak",location_group = "Bincho", jp_name = "つむぎてエイランチのビンチョ - ふたご山"),
    "SoldierB Bincho - Restaurant Basement Planks Over Lava": BFMLocationData("Restaurant Basement Planks Over Lava",location_group = "Bincho", jp_name = "へいしバーベックのビンチョ - バーの地下"),
    "KnightA Bincho - Mine Conveyor Belt Room": BFMLocationData("Mine Conveyor Belt Room",location_group = "Bincho", jp_name = "きしニックのビンチョ - ビンチョタイト採掘場"),
    "CookA Bincho - Misteria Underground Lake": BFMLocationData("Misteria Underground Lake",location_group = "Bincho", jp_name = "しょくじがかりリブのビンチョ - 地底湖"),
    "Acrobat Bincho - Steamwood Forest": BFMLocationData("Steamwood Forest",location_group = "Bincho", jp_name = "きょくげいしナムルのビンチョ - スチームウッドの森"),
    "MercenB Bincho - Restaurant Basement Bowling 2": BFMLocationData("Restaurant Basement Bowling 2",location_group = "Bincho", jp_name = "ようへいカルビのビンチョ - バーの地下"),
    "Janitor Bincho - Frozen Palace Blue Eye Door": BFMLocationData("Frozen Palace Blue Eye Door",location_group = "Bincho", jp_name = "ベんじょのニクジルのビンチョ - フリーズパレス"),
    "Artisan Bincho - Island of Dragons": BFMLocationData("Island of Dragons",location_group = "Bincho", jp_name = "かじやのトックのビンチョ - ガンリュー島"),
    "CarpentC Bincho - Mine Conveyor Belt Room": BFMLocationData("Mine Conveyor Belt Room",location_group = "Bincho", jp_name = "おやかたマーダレーのビンチョ - ビンチョタイト採掘場"),
    "MusicianC Bincho - Frozen Palace Green Eye Maze": BFMLocationData("Frozen Palace Green Eye Maze",location_group = "Bincho", jp_name = "ビビンバッハガくしのビンチョ - フリーズパレス"),
    "Knitter Bincho - Twinpeak Path to Skullpion": BFMLocationData("Twinpeak Path to Skullpion",location_group = "Bincho", jp_name = "ぬのがかりビセットのビンチョ - ヘルズバレー"),
    "Chef Bincho - Frozen Palace Crate Pile": BFMLocationData("Frozen Palace Crate Pile",location_group = "Bincho", jp_name = "クーパー・シェフのビンチョ - フリーズパレス"),
    "MercenA Bincho - Restaurant Basement Bowling 1": BFMLocationData("Restaurant Basement Bowling 1",location_group = "Bincho", jp_name = "ようへいロースウのビンチョ - バーの地下"),
    "Chief Bincho - Misteria Underground Lake": BFMLocationData("Misteria Underground Lake",location_group = "Bincho", jp_name = "ビールかんとくのビンチョ - 地底湖"),
    "CookB Bincho - Upper Mines": BFMLocationData("Upper Mines Behind Posion",location_group = "Bincho", jp_name = "ムッシュ・ワギュウのビンチョ - アリの巣"),
    "Conductor Bincho - Upper Mines Ant Parade": BFMLocationData("Upper Mines Ant Parade",location_group = "Bincho", jp_name = "おんがくだんちょうのビンチョ - アリの巣"),
    "Butcher Bincho - Frozen Palace Atrium Right Balcony": BFMLocationData("Frozen Palace Atrium Right Balcony",location_group = "Bincho", jp_name = "にくきりハーラミンのビンチョ - フリーズパレス"),
    "KnightC Bincho - Restaurant Basement Dark Platform Maze 3": BFMLocationData("Restaurant Basement Dark Platform Maze 3",location_group = "Bincho", jp_name = "きしコブクローネのビンチョ - バーの地下"),
    "Doctor Bincho - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Bincho", jp_name = "モルホンいしのビンチョ - ふたご山"),
    "KnightD Bincho - Upper Mines Before Digging": BFMLocationData("Upper Mines Before Digging",location_group = "Bincho", jp_name = "きしだんちょうのビンチョ - アリの巣"),
    "Alchemist Bincho - Frozen Palace Red Eye Maze": BFMLocationData("Frozen Palace Red Eye Maze",location_group = "Bincho", jp_name = "れんきんじゃつしのビンチョ - フリーズパレス"),
    "Librarian Bincho - Restaurant Basement Near Rotating Platforms": BFMLocationData("Restaurant Basement Near Rotating Platforms",location_group = "Bincho", jp_name = "ゾウモッツしょきのビンチョ - バーの地下"),
    "Minku - Grillin Village Near Twinpeak": BFMLocationData("Upper Grillin Village",location_group = "Minku", jp_name = "ミンクー - アミヤクイ村"),
    "Minku - Somnolent Forest Hidden Path": BFMLocationData("Somnolent Forest",location_group = "Minku", jp_name = "ミンクー - すいまの森"),
    "Minku - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Minku", jp_name = "ミンクー - ふたご山"),
    "Minku - Grillin Village Above Gondola": BFMLocationData("Upper Grillin Village",location_group = "Minku", jp_name = "ミンクー - ゴンドラの上"),
    "Minku - Skullpion Arena": BFMLocationData("Skullpion Arena",location_group = "Minku", jp_name = "ミンクー - ヘルズバレー"),
    "Minku - Steamwood Forest": BFMLocationData("Steamwood Forest",location_group = "Minku", jp_name = "ミンクー - スチームウッドの森"),
    "Minku - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Minku", jp_name = "ミンクー - すいまの森の川"),
    "Minku - Twinpeak End of Stream": BFMLocationData("Twinpeak Around the Bend",location_group = "Minku", jp_name = "ミンクー - ふたご山の川"),
    "Minku - Misteria Underground Lake": BFMLocationData("Misteria Underground Lake",location_group = "Minku", jp_name = "ミンクー - 地底湖"),
    "Minku - Grillin Reservoir": BFMLocationData("Grillin Reservoir",location_group = "Minku", jp_name = "ミンクー - アミヤクイ村貯水池"),
    "Minku - Upper Mines Below Big Fan": BFMLocationData("Upper Mines Big Fan Room",location_group = "Minku", jp_name = "ミンクー - アリの巣"),
    "Minku - Upper Mines": BFMLocationData("Upper Mines",location_group = "Minku", jp_name = "ミンクー - アリの巣の入り口"),
    "Minku - Near Wind Scroll": BFMLocationData("Wind Scroll",location_group = "Minku", jp_name = "ミンクー - アミヤクイ村の火山"),
    "500 Drans Chest - Somnolent Forest Behind Steam": BFMLocationData("Somnolent Forest Behind Steam", jp_name = "500ドランのはこ - すいまの森"),
    "Old Crown Chest - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Chest", jp_name = "しめったしょもつのはこ - すいまの森"),
    "Aged Coin Chest - Steamwood Forest": BFMLocationData("Steamwood Forest",location_group = "Chest", jp_name = "あなあきコインのはこ - スチームウッドの森"),
    "200 Drans Chest - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Chest", jp_name = "200ドランのはこ - ふたご山"),
    "Old Book Chest - Twinpeak Around the Bend": BFMLocationData("Twinpeak Around the Bend",location_group = "Chest", jp_name = "しめったしょもつのはこ - ふたご山"),
    "Rock Chest - Twinpeak Second Peak": BFMLocationData("Twinpeak Second Peak",location_group = "Chest", jp_name = "かがやくいしのはこ - ふたご山"),
    "Dagger Chest - Twinpeak Rope Bridge": BFMLocationData("Twinpeak Rope Bridge",location_group = "Chest", jp_name = "ふるびたたんけんのはこ - ふたご山"),
    "Bracelet Chest - Twinpeak Entrance": BFMLocationData("Twinpeak Entrance",location_group = "Chest", jp_name = "おおきなうでわのはこ - ふたご山"),
    "200 Drans Chest - Twinpeak Path to Skullpion": BFMLocationData("Twinpeak Path to Skullpion",location_group = "Chest", jp_name = "200ドランのはこ - ヘルズバレー"),
    "Red Eye Chest - Frozen Palace Red Eye Room": BFMLocationData("Frozen Palace Red Eye Room",location_group = "Chest", jp_name = "レッドアイのはこ - フリーズパレス"),
    "Blue Eye Chest - Frozen Palace Red Eye Maze": BFMLocationData("Frozen Palace Red Eye Maze",location_group = "Chest", jp_name = "ブルーアイのはこ - フリーズパレス"),
    "Green Eye Chest - Frozen Palace Green Eye Maze": BFMLocationData("Frozen Palace Green Eye Maze",location_group = "Chest", jp_name = "グリーンアイのはこ - フリーズパレス"),
    "Red Shoes Chest - Frozen Palace Atrium Left Balcony": BFMLocationData("Frozen Palace Atrium Left Balcony",location_group = "Chest", jp_name = "まっかなボロぐつのはこ - フリーズパレス"),
    "Long Tube Chest - Frozen Palace Red Eye Door": BFMLocationData("Frozen Palace Red Eye Door",location_group = "Chest", jp_name = "とんがりばうのはこ - フリーズパレス"),
    "500 Drans Chest - Island of Dragons": BFMLocationData("Island of Dragons",location_group = "Chest", jp_name = "500ドランのはこ - ガンリュー島"),
    "Shield Chest - Restaurant Basement Bowling 1": BFMLocationData("Restaurant Basement Bowling 1",location_group = "Chest", jp_name = "ふるびたタテのはこ - バーの地下"),
    "Odd Hat Chest - Restaurant Basement Bowling 1": BFMLocationData("Restaurant Basement Bowling 1",location_group = "Chest", jp_name = "ひびわれ・かめんのはこ - バーの地下"),
    "Old Sword Chest - Restaurant Basement": BFMLocationData("Restaurant Basement",location_group = "Chest", jp_name = "さびたつるぎのはこ - バーの地下"),
    "Old Shirt Chest - Grillin Reservoir": BFMLocationData("Grillin Reservoir",location_group = "Chest", jp_name = "よれよれシャツのはこ - アミヤクイ村貯水池"),
    "300 Drans Chest - Restaurant Basement": BFMLocationData("Restaurant Basement",location_group = "Chest", jp_name = "300ドランのはこ - バーの地下"),
    "Old Pipe Chest - Restaurant Basement Planks Over Lava": BFMLocationData("Restaurant Basement Planks Over Lava",location_group = "Chest", jp_name = "あなあきこんぼうのはこ - バーの地下"),
    "Powder Chest - Restaurant Basement Teleport Maze": BFMLocationData("Restaurant Basement Teleport Maze",location_group = "Chest", jp_name = "しろいこなのはこ - バーの地下"),
    "Helmet Chest - Restaurant Basement Dark Platform Maze 3": BFMLocationData("Restaurant Basement Dark Platform Maze 3",location_group = "Chest", jp_name = "ゆがんだツボのはこ - バーの地下"),
    "Old Glove Chest - Misteria Underground Lake": BFMLocationData("Misteria Underground Lake",location_group = "Chest", jp_name = "ほつれたてぶくろのはこ - 地底湖"),
    "Cloth Chest - Restaurant Basement": BFMLocationData("Restaurant Basement",location_group = "Chest", jp_name = "あつでのまきぬののはこ - バーの地下"),
    "Used Boot Chest - Grillin Reservoir": BFMLocationData("Grillin Reservoir",location_group = "Chest", jp_name = "よれよれながぐつのはこ - アミヤクイ村貯水池"),
    "White Cloth Chest - Frozen Palace Green Eye Maze": BFMLocationData("Frozen Palace Green Eye Maze",location_group = "Chest", jp_name = "しろいぬのきれのはこ - フリーズパレス"),
    "Red Cloth Chest - Frozen Palace Green Eye Maze": BFMLocationData("Frozen Palace Green Eye Maze",location_group = "Chest", jp_name = "あかいぬのきれのはこ - フリーズパレス"),
    "Black Cloth Chest - Frost Dragon Door": BFMLocationData("Frost Dragon Door",location_group = "Chest", jp_name = "くろいぬのきれのはこ - フリーズパレス"),
    "Glasses Chest - Somnolent Forest": BFMLocationData("Somnolent Forest",location_group = "Chest", jp_name = "ひびわれメガネのはこ - すいまの森"),
    "Large Tool Chest - Upper Mines": BFMLocationData("Upper Mines Behind Posion",location_group = "Chest", jp_name = "スルドイどうぐのはこ - アリの巣"),
    "Odd Bone Chest - Upper Mines": BFMLocationData("Upper Mines Behind Posion",location_group = "Chest", jp_name = "しんぴのほねぐみのはこ - アリの巣"),
    "Armor Chest - Reservoir Tunnel": BFMLocationData("Reservoir Tunnel",location_group = "Chest", jp_name = "ヘこんだヨロイのはこ - アミヤクイ村貯水池"),
    "Lumina - Spiral Tower": BFMLocationData("Spiral Tower",location_group = "Equipment", jp_name = "レイガンド - らせんの塔"),
    "Item 1 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery", jp_name = "アイテム 1 - ふっくらパン屋ブレッド"),
    "Item 2 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery", jp_name = "アイテム 2 - ふっくらパン屋ブレッド"),
    "Item 3 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery", jp_name = "アイテム 3 - ふっくらパン屋ブレッド"),
    "Item 4 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery", jp_name = "アイテム 4 - ふっくらパン屋ブレッド"),
    "Item 5 - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery", jp_name = "アイテム 5 - ふっくらパン屋ブレッド"),
    "Item 6 (JamBread) - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery", jp_name = "アイテム 6 - ふっくらパン屋ブレッド"),
    "Item 7 (Biscuit) - Bakery": BFMLocationData("Grillin Village",location_group = "Bakery", jp_name = "アイテム 7 - ふっくらパン屋ブレッド"),
    "Item 1 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant", jp_name = "アイテム 1 - ダクレイズ バー"),
    "Item 2 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant", jp_name = "アイテム 2 - ダクレイズ バー"),
    "Item 3 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant", jp_name = "アイテム 3 - ダクレイズ バー"),
    "Item 4 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant", jp_name = "アイテム 4 - ダクレイズ バー"),
    "Item 5 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant", jp_name = "アイテム 5 - ダクレイズ バー"),
    "Item 6 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant", jp_name = "アイテム 6 - ダクレイズ バー"),
    "Item 7 - Restaurant": BFMLocationData("Grillin Village",location_group = "Restaurant", jp_name = "アイテム 7 - ダクレイズ バー"),
    "Item 1 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 1 - 雑貨屋アイのみせ"),
    "Item 2 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 2 - 雑貨屋アイのみせ"),
    "Item 3 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 3 - 雑貨屋アイのみせ"),
    "Item 4 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 4 - 雑貨屋アイのみせ"),
    "Item 5 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 5 - 雑貨屋アイのみせ"),
    "Item 6 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 6 - 雑貨屋アイのみせ"),
    "Item 7 - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 7 - 雑貨屋アイのみせ"),
    "Item 8 (Orange) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 8 - 雑貨屋アイのみせ"),
    "Item 9 (EX-Drink) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 9 - 雑貨屋アイのみせ"),
    "Item 10 (H-Mint) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 10 - 雑貨屋アイのみせ"),
    "Item 11 (Riceball) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 11 - 雑貨屋アイのみせ"),
    "Item 12 (Neat Ball) - Grocery": BFMLocationData("Grillin Village",location_group = "Grocery", jp_name = "アイテム 12 - 雑貨屋アイのみせ"),
    "Musashi - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop", jp_name = "ムサシ - トーイざんす"),
    "Bee Plant - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop", jp_name = "ビー・プラント - トーイざんす"),
    "Soldier1 - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop", jp_name = "ル・コアールヘい1 - トーイざんす"),
    "Soldier2 - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop", jp_name = "ル・コアールヘい2 - トーイざんす"),
    "Rootrick - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop", jp_name = "ボルドーしょうい - トーイざんす"),
    "Steam Knight - Toy Shop": BFMLocationData("Toy Shop Series 1",location_group = "Toy Shop", jp_name = "スチーム・ナイト - トーイざんす"),
    "Soldier3 - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop", jp_name = "ル・コアールヘい3 - トーイざんす"),
    "Herb Plant - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop", jp_name = "ハーブ・プラント - トーイざんす"),
    "King Man Eater - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop", jp_name = "キングマンイーター - トーイざんす"),
    "Magician - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop", jp_name = "マジシャン - トーイざんす"),
    "Sleepie - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop", jp_name = "スリーピー - トーイざんす"),
    "Skullpion - Toy Shop": BFMLocationData("Toy Shop Series 2",location_group = "Toy Shop", jp_name = "スカル゠ピオン - トーイざんす"),
    "Relic Vambee - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop", jp_name = "レリクスヴヌンビ - トーイざんす"),
    "Vambee Soldier - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop", jp_name = "ヴヌンビへい - トーイざんす"),
    "Bowler - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop", jp_name = "ボウラー - トーイざんす"),
    "Cure Worm - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop", jp_name = "キュアワーム - トーイざんす"),
    "Bubbles - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop", jp_name = "リキュールちゃうい - トーイざんす"),
    "Relic Keeper - Toy Shop": BFMLocationData("Toy Shop Series 3",location_group = "Toy Shop", jp_name = "レリクスキーパー - トーイざんす"),
    "Penguin - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop", jp_name = "フェイクペンギン - トーイざんす"),
    "Haya Wolf - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop", jp_name = "カラテウルフ - トーイざんす"),
    "Slow Guy - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop", jp_name = "スローガイ - トーイざんす"),
    "Stomp Golem - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop", jp_name = "ストンプゴーレム - トーイざんす"),
    "Gingerelle - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop", jp_name = "ブランディたいい - トーイざんす"),
    "Frost Dragon - Toy Shop": BFMLocationData("Toy Shop Series 4",location_group = "Toy Shop", jp_name = "フロストドラグーン - トーイざんす"),
    "GiAnt - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop", jp_name = "ジャイアント - トーイざんす"),
    "Toad Stool - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop", jp_name = "トードストゥール - トーイざんす"),
    "Ed & Ben - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop", jp_name = "エドとベーン - トーイざんす"),
    "Topo - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop", jp_name = "トポ - トーイざんす"),
    "Colonel Capricola - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop", jp_name = "ウォッカたいき - トーイざんす"),
    "Queen Ant - Toy Shop": BFMLocationData("Toy Shop Series 5",location_group = "Toy Shop", jp_name = "アントヒルクィーン - トーイざんす"),
    "Improved Fusion (Artisan) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech", jp_name = "真雷光丸 - ヤクイニック城"),
    "Dashing Pierce (Maid) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech", jp_name = "ダッシュつき - ヤクイニック城"),
    "Shish Kebab (Clown) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech", jp_name = "くしざし - ヤクイニック城"),
    "Crosswise Cut (KnightB) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech", jp_name = "じうもんじぎり - ヤクイニック城"),
    "Tenderize (KnightA) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech", jp_name = "まきわりダイナマイト - ヤクイニック城"),
    "Desperado Attack (KnightC) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech", jp_name = "デスペラードアタック - ヤクイニック城"),
    "Rumparoni Special (KnightD) - Allucaneet Castle": BFMLocationData("Castle",location_group = "Tech", jp_name = "タンシオーネ・クロスアタック - ヤクイニック城"),
    "Earth Scroll - Twinpeak First Peak": BFMLocationData("Twinpeak Around the Bend",location_group = "Scroll", jp_name = "チのまき - ふたご山"),
    "Water Scroll - Grillin Reservoir": BFMLocationData("Grillin Reservoir",location_group = "Scroll", jp_name = "ミズのまき - アミヤクイ村貯水池"),
    "Fire Scroll - Island of Dragons": BFMLocationData("Island of Dragons",location_group = "Scroll", jp_name = "ヒのまき - ガンリュー島"),
    "Wind Scroll - Grillin Volcano": BFMLocationData("Wind Scroll",location_group = "Scroll", jp_name = "カゼのまき - アミヤクイ村の火山"),
    "Sky Scroll - Sky Island": BFMLocationData("Sky Island",location_group = "Scroll", jp_name = "ソラのまき - 空の巻の地"),
    "Defeat Earth Crest Guardian - Skullpion Arena": BFMLocationData("Skullpion Arena",location_group = "Core", jp_name = "倒すスカル゠ピオン - ヘルズバレー"),
    "Defeat Water Crest Guardian - Relic Keeper Arena": BFMLocationData("Relic Keeper Arena",location_group = "Core", jp_name = "倒すレリクスキーパー - バーの地下"),
    "Defeat Fire Crest Guardian - Frost Dragon Arena": BFMLocationData("Frost Dragon Arena",location_group = "Core", jp_name = "倒すフロストドラグーン - フリーズパレス"),
    "Defeat Wind Crest Guardian - Queen Ant Arena": BFMLocationData("Queen Ant Arena",location_group = "Core", jp_name = "倒すアントヒルクィーン - アリの巣"),
    "lvl 2 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 2 ちから"),
    "lvl 3 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 3 ちから"),
    "lvl 4 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 4 ちから"),
    "lvl 5 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 5 ちから"),
    "lvl 6 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 6 ちから"),
    "lvl 7 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 7 ちから"),
    "lvl 8 Body - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 8 ちから"),
    "lvl 9 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 9 ちから"),
    "lvl 10 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 10 ちから"),
    "lvl 11 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 11 ちから"),
    "lvl 12 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 12 ちから"),
    "lvl 13 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 13 ちから"),
    "lvl 14 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 14 ちから"),
    "lvl 15 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 15 ちから"),
    "lvl 16 Body - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 16 ちから"),
    "lvl 17 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 17 ちから"),
    "lvl 18 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 18 ちから"),
    "lvl 19 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 19 ちから"),
    "lvl 20 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 20 ちから"),
    "lvl 21 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 21 ちから"),
    "lvl 22 Body - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 22 ちから"),
    "lvl 23 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 23 ちから"),
    "lvl 24 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 24 ちから"),
    "lvl 25 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 25 ちから"),
    "lvl 26 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 26 ちから"),
    "lvl 27 Body - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 27 ちから"),
    "lvl 28 Body - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 28 ちから"),
    "lvl 29 Body - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 29 ちから"),
    "lvl 30 Body - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 30 ちから"),
    "lvl 2 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 2 こころ"),
    "lvl 3 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 3 こころ"),
    "lvl 4 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 4 こころ"),
    "lvl 5 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 5 こころ"),
    "lvl 6 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 6 こころ"),
    "lvl 7 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 7 こころ"),
    "lvl 8 Mind - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 8 こころ"),
    "lvl 9 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 9 こころ"),
    "lvl 10 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 10 こころ"),
    "lvl 11 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 11 こころ"),
    "lvl 12 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 12 こころ"),
    "lvl 13 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 13 こころ"),
    "lvl 14 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 14 こころ"),
    "lvl 15 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 15 こころ"),
    "lvl 16 Mind - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 16 こころ"),
    "lvl 17 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 17 こころ"),
    "lvl 18 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 18 こころ"),
    "lvl 19 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 19 こころ"),
    "lvl 20 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 20 こころ"),
    "lvl 21 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 21 こころ"),
    "lvl 22 Mind - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 22 こころ"),
    "lvl 23 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 23 こころ"),
    "lvl 24 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 24 こころ"),
    "lvl 25 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 25 こころ"),
    "lvl 26 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 26 こころ"),
    "lvl 27 Mind - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 27 こころ"),
    "lvl 28 Mind - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 28 こころ"),
    "lvl 29 Mind - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 29 こころ"),
    "lvl 30 Mind - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 30 こころ"),
    "lvl 2 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 2 らいこう丸"),
    "lvl 3 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 3 らいこう丸"),
    "lvl 4 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 4 らいこう丸"),
    "lvl 5 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 5 らいこう丸"),
    "lvl 6 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 6 らいこう丸"),
    "lvl 7 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 7 らいこう丸"),
    "lvl 8 Fus - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 8 らいこう丸"),
    "lvl 9 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 9 らいこう丸"),
    "lvl 10 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 10 らいこう丸"),
    "lvl 11 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 11 らいこう丸"),
    "lvl 12 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 12 らいこう丸"),
    "lvl 13 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 13 らいこう丸"),
    "lvl 14 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 14 らいこう丸"),
    "lvl 15 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 15 らいこう丸"),
    "lvl 16 Fus - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 16 らいこう丸"),
    "lvl 17 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 17 らいこう丸"),
    "lvl 18 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 18 らいこう丸"),
    "lvl 19 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 19 らいこう丸"),
    "lvl 20 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 20 らいこう丸"),
    "lvl 21 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 21 らいこう丸"),
    "lvl 22 Fus - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 22 らいこう丸"),
    "lvl 23 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 23 らいこう丸"),
    "lvl 24 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 24 らいこう丸"),
    "lvl 25 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 25 らいこう丸"),
    "lvl 26 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 26 らいこう丸"),
    "lvl 27 Fus - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 27 らいこう丸"),
    "lvl 28 Fus - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 28 らいこう丸"),
    "lvl 29 Fus - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 29 らいこう丸"),
    "lvl 30 Fus - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 30 らいこう丸"),
    "lvl 2 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 2 レイガンド"),
    "lvl 3 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 3 レイガンド"),
    "lvl 4 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 4 レイガンド"),
    "lvl 5 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 5 レイガンド"),
    "lvl 6 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 6 レイガンド"),
    "lvl 7 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 7 レイガンド"),
    "lvl 8 Lum - Menu": BFMLocationData("Grillin Village",location_group = "Level", jp_name = "LV 8 レイガンド"),
    "lvl 9 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 9 レイガンド"),
    "lvl 10 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 10 レイガンド"),
    "lvl 11 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 11 レイガンド"),
    "lvl 12 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 12 レイガンド"),
    "lvl 13 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 13 レイガンド"),
    "lvl 14 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 14 レイガンド"),
    "lvl 15 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 15 レイガンド"),
    "lvl 16 Lum - Menu": BFMLocationData("Skullpion Arena",location_group = "Level", jp_name = "LV 16 レイガンド"),
    "lvl 17 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 17 レイガンド"),
    "lvl 18 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 18 レイガンド"),
    "lvl 19 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 19 レイガンド"),
    "lvl 20 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 20 レイガンド"),
    "lvl 21 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 21 レイガンド"),
    "lvl 22 Lum - Menu": BFMLocationData("Relic Keeper Arena",location_group = "Level", jp_name = "LV 22 レイガンド"),
    "lvl 23 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 23 レイガンド"),
    "lvl 24 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 24 レイガンド"),
    "lvl 25 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 25 レイガンド"),
    "lvl 26 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 26 レイガンド"),
    "lvl 27 Lum - Menu": BFMLocationData("Frost Dragon Arena",location_group = "Level", jp_name = "LV 27 レイガンド"),
    "lvl 28 Lum - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 28 レイガンド"),
    "lvl 29 Lum - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 29 レイガンド"),
    "lvl 30 Lum - Menu": BFMLocationData("Queen Ant Arena",location_group = "Level", jp_name = "LV 30 レイガンド"),
}

sphere_one: List[str] = [
    "Guard Bincho - Somnolent Forest",
    "Seer Bincho - Somnolent Forest",
    "Hawker Bincho - Somnolent Forest",
    "MusicianB Bincho - Steamwood Forest",
    "SoldierA Bincho - Twinpeak Entrance",
    "Acrobat Bincho - Steamwood Forest"
]

en_standard_location_name_to_id: Dict[str, int] = {name: location_base_id + index for index, name in enumerate(location_table)}
jp_location_name_to_id: Dict[str, int] = {location_table[name].jp_name: location_base_id + index + jp_id_offset for index, name in enumerate(location_table)}

all_locations = location_table.copy()


location_name_groups: Dict[str, Set[str]] = {}
for loc_name, loc_data in location_table.items():
    loc_group_name = loc_name.split(" - ", 1)[1]
    location_name_groups.setdefault(loc_group_name, set()).add(loc_name)
    if loc_data.location_group:
        location_name_groups.setdefault(loc_data.location_group, set()).add(loc_name)


en_table_ids_to_hint: List[int] = []
jp_table_ids_to_hint: List[int] = []
for loc_name, loc_id in en_standard_location_name_to_id.items():
    if(location_table[loc_name].location_group):
        #if(not location_table[loc_name].location_group in ["Bakery", "Equipment", "Minku", "Restaurant", "Grocery", "Toy Shop", "Tech"]):
        if(location_table[loc_name].location_group in ["Bincho", "Chest"]):
            en_table_ids_to_hint.append(loc_id)
            jp_table_ids_to_hint.append(loc_id + jp_id_offset)
    else:
        en_table_ids_to_hint.append(loc_id)
        jp_table_ids_to_hint.append(loc_id + jp_id_offset)

standard_location_name_to_id = en_standard_location_name_to_id | jp_location_name_to_id
