from typing import Dict, NamedTuple, Set, Optional, List

progression_state_table = [
    0x000a: "zipline down gondola",
    0x0014: "Rescue Leno",
    0x001e: "Talk to the mayor after rescuing Leno",
    0x0028: "Jon asks for food and water",
    0x0032: "Feed Jon",
    0x003c: "Find Jon's Key",
    0x0046: "Free Jon",
    0x0050: "Give Jon the 4 trees and understand about the five scrolls",
    0x005a: "Find Bracelet",
    0x0064: "Equip L-Brace",
    0x006e: "Agree to help the mayor with Steamwood",
    0x0078: "Talk to Fores and start the Steamwood event",
    0x0082: "Fix Steamwood",
    0x0085: "Collect the Earth Scroll",
    0x0087: "Meet Jon after collecting Earth Scroll",
    0x008c: "Talk to Geezer about opening hells valley",
    0x0096: "have Geezer permission to face the Earth Crest Guardian",
    0x00a0: "Allies open the gate to Hell's Valley",
    0x00c8: "Acquire your first crest",
    0x00d2: "The Mayor says you can get the key to the coal mine with the man from the mill",
    0x00dc: "Acquire Mine's Key",
    0x00e6: "Acquire Misteria Bloom",
    0x00f0: "Give Misteria to Mayor and Mayor wonders if Hotelo is alright",
    0x00fa: "Meet Hotelo on Twinpeak Mountain and return to village instead",
    0x0104: "Meet Hotelo on Twinpeak Mountain and go after Aqualin",
    0x010e: "Get Aqualin",
    0x0118: "Give Aqualin to Hotelo",
    0x0122: "Talk to Tim after saving him",
    0x012c: "Tim became a Vambee/ Tim is Saved",
    0x0136: "Talk to the drunk and discover you",
    0x0140: "Wanda talks about the vambees' nest",
    0x014a: "Meet the restaurant owner at the basement",
    0x0172: "Open all blue eyes",
    0x017c: "Get the Ugly Belt",
    0x0181: "Equip the L-Belt",
    0x0186: "The owner of the restaurant says he needs the rope",
    0x0190: "Something is happening at the church at 2 am",
    0x019a: "Enter the church infested with vambees",
    0x01a4: "Exit the church infested with vambees",
    0x01ae: "The Father asks you to retrieve Church Bell",
    0x01cc: "Collected water scroll",
    0x01d1: "Interacting with the church bell (does not require talking to priest)",
    0x01d6: "Give the Church Bell to the priest",
    0x01e0: "Return the bell to the village",
    0x0258: "Acquire your second crest",
    0x0276: "Fix the Village Well",
    0x0280: "The mayor's wife asks you to fix the Gondola Gizmo",
    0x028a: "Carpenters inform you of the appearance of the item needed to fix the Gondola Gizmo",
    0x0294: "Deliver the Gizmo Gondola",
    0x029e: "A fire starts in the village",
    0x02a8: "Put out fire",
    0x02b2: "Mrs. Govern thanks you and tells musashi about the thieves",
    0x02bc: "Get the calendar and rock salt",
    0x02c6: "Use salt on the slug",
    0x02d0: "collect the fire scroll",
    0x02da: "Save the princess",
    0x02e4: "Rescue princess Filet and take her to the castle",
    0x02ee: "The mercenaries give you the location",
    0x02f0: "Reach the frost palace gate for the first time",
    0x02f8: "Meet Gingerelle",
    0x0302: "Melt boss door",
    0x030c: "Open and enter the big gate of the 3 eyes in the ice palace",
    0x0384: "Defeat Frost Dragon",
    0x0398: "Complete 4 chapter",
    0x03a2: "Start 5 chapter mayor says to visit shops",
    0x03ac: "Talk to a shop about the missing profits",
    0x03b6: "The princess disappeared and took the village profits with her",
    0x03c0: "go down fixed gondola",
    0x03ca: "Receive Handle 0",
    0x03d4: "Pick up Profits",
    0x03e8: "Give back the profits",
    0x03f2: "Finish the events of the second Steamwood",
    0x044c: "Get the Wind Scroll",
    0x0460: "break your own bincho field",
    0x047e: "See the mutant ant at the mountain entrance",
    0x0488: "select to take gondola to ant",
    0x0492: "Expel the mutant ant",
    0x04b0: "Defeat Queen Ant",
    0x04ba: "Go up to the sky for the first time",
    0x0514: "Defeat Ben",
    0x0578: "Defeat Ed",
    0x05dc: "Defeat Topo",
    0x0636: "Start the race against Dark Lumina and DL2 fight",
    0x0640: "DL3 fight",
    0x064a: "end of Credits (would you like to save)",
]

    0x3000: "Castle Outside", 
        0x029e: "A fire starts in the village",
        0x03b6: "The princess disappeared and took the village profits with her",
        0x03c0: "go down fixed gondola",
    0x3003: "Castle Meeting Room", 
        0x008c: "Talk to Geezer about opening hells valley",
        0x0096: "have Geezer permission to face the Earth Crest Guardian",
        0x00c8: "Acquire your first crest",
        0x0280: "The mayor's wife asks you to fix the Gondola Gizmo",
        0x028a: "Carpenters inform you of the appearance of the item needed to fix the Gondola Gizmo",
        0x0294: "Deliver the Gizmo Gondola",
        0x02da: "Save the princess",
        0x03ac: "Talk to a shop about the missing profits",
        0x03b6: "The princess disappeared and took the village profits with her",
    0x3004: "Castle Gondola", 
        0x03b6: "The princess disappeared and took the village profits with her",
        0x03c0: "go down fixed gondola",
    0x3014: "Somnolent Forest", 
        0x0032: "Feed Jon",
        0x04b0: "Defeat Queen Ant",
        0x04ba: "Go up to the sky for the first time",
    0x301b: "Meandering Forest", 
        0x0032: "Feed Jon",
        0x02ee: "The mercenaries give you the location",
        0x02f8: "Meet Gingerelle",
	#0x301c: "Steamwood Forest", 
    0x301e: "Steamwood Outside", 
        0x0078: "Talk to Fores and start the Steamwood event",
        0x0082: "Fix Steamwood",
        0x03c0: "go down fixed gondola",
        0x03ca: "Receive Handle 0",
	#0x3021: "Island of Dragons", 
    0x3022: "Graveyard", 
        0x0032: "Feed Jon",
	0x3024: "Skullpion Arena", 
        0x00a0: "Allies open the gate to Hell's Valley",
        0x00c8: "Acquire your first crest",
    0x3025: "Twinpeak Entrance", 
        0x0014: "Rescue Leno",
        0x001e: "Talk to the mayor after rescuing Leno",
        0x0028: "Jon asks for food and water",
        0x0032: "Feed Jon",
        0x003c: "Find Jon's Key",
        0x0046: "Free Jon",
        0x00f0: "Give Misteria to Mayor and Mayor wonders if Hotelo is alright",
    0x3026: "Twinpeak Around the Bend", 
        0x0082: "Fix Steamwood",
        0x00f0: "Give Misteria to Mayor and Mayor wonders if Hotelo is alright",
    0x3029: "Twinpeak Second Peak", 
        0x0050: "Give Jon the 4 trees and understand about the five scrolls",
        0x005a: "Find Bracelet",
        0x0104: "Meet Hotelo on Twinpeak Mountain and go after Aqualin",
        0x010e: "Get Aqualin",
	#0x302a: "Twinpeak Rafting", 
	0x302b: "Twinpeak Path to Skullpion", 
        0x008c: "Talk to Geezer about opening hells valley",
        0x0096: "have Geezer permission to face the Earth Crest Guardian",
        0x00a0: "Allies open the gate to Hell's Valley",
	0x302c: "Twinpeak Waterfall Cave 2", 
        0x00f0: "Give Misteria to Mayor and Mayor wonders if Hotelo is alright",
        0x00fa: "Meet Hotelo on Twinpeak Mountain and return to village instead",
        0x0104: "Meet Hotelo on Twinpeak Mountain and go after Aqualin",
        0x010e: "Get Aqualin",
        0x0118: "Give Aqualin to Hotelo",
	0x3034: "Restaurant Basement Entrance", 
        0x0140: "Wanda talks about the vambees' nest",
        0x014a: "Meet the restaurant owner at the basement",
        0x0172: "Open all blue eyes",
        0x017c: "Get the Ugly Belt",
	0x3042: "Relic Keeper Arena", 
        0x01e0: "Return the bell to the village",
	0x3047: "Misteria Underground Lake", 
        0x00dc: "Acquire Mine's Key",
	0x304b: "Lower Mine Scrap Depository", 
        0x0280: "The mayor's wife asks you to fix the Gondola Gizmo",
        0x028a: "Carpenters inform you of the appearance of the item needed to fix the Gondola Gizmo",
	#0x304c: "Restaurant Basement Outside Relic Keeper", 
	0x304d: "Grillin Reservoir Tunnel", 
        0x03f2: "Finish the events of the second Steamwood",
        0x044c: "Get the Wind Scroll",
	0x304e: "Grillin Reservoir", 
        #check if progression state affects Rope to climb
	#0x3051: "Chapter 3 Church Vambee Fight",
	0x305c: "Frozen Palace Lobby", 
        #0x02f0: "Reach the frost palace gate for the first time",
        0x02f8: "Meet Gingerelle",
        0x0302: "Melt boss door",
	0x3066: "Frozen Palace Dragon Church", 
        0x030c: "Open and enter the big gate of the 3 eyes in the ice palace",
	#0x3068: "Frozen Palace Courtyard", 
	#0x3069: "Chapter 4 Village on Fire", 
	#0x306f: "Upper Mine Big Fan", 
	0x3072: "Upper Mine Gondola Station", 
        0x0492: "Expel the mutant ant", 
	#0x3074: "Upper Mine Above Queen Ant", 
	0x3075: "Queen Ant Arena",
        0x0492: "Expel the mutant ant", #is this even needed?
	#0x3081: "Sky Island",    
    0x1010: "Chapter 2 Grillin Village", 0x000a: "zipline down gondola",
        0x0014: "Rescue Leno",
        0x001e: "Talk to the mayor after rescuing Leno",
        0x0028: "Jon asks for food and water",
        0x0032: "Feed Jon",
        0x003c: "Find Jon's Key",
        0x0046: "Free Jon",
        0x0050: "Give Jon the 4 trees and understand about the five scrolls",
        0x005a: "Find Bracelet",
        0x0064: "Equip L-Brace",
        0x006e: "Agree to help the mayor with Steamwood",
        0x0078: "Talk to Fores and start the Steamwood event",
        0x0082: "Fix Steamwood",
        0x0085: "Collect the Earth Scroll",
        0x0087: "Meet Jon after collecting Earth Scroll",
        0x008c: "Talk to Geezer about opening hells valley",
        0x0096: "have Geezer permission to face the Earth Crest Guardian",
        0x00a0: "Allies open the gate to Hell's Valley",
	0x1052: "Chapter 3 Grillin Village", 
        0x00c8: "Acquire your first crest",
        0x00d2: "The Mayor says you can get the key to the coal mine with the man from the mill",
        0x00dc: "Acquire Mine's Key",
        0x00e6: "Acquire Misteria Bloom",
        0x00f0: "Give Misteria to Mayor and Mayor wonders if Hotelo is alright",
        0x00fa: "Meet Hotelo on Twinpeak Mountain and return to village instead",
        0x0104: "Meet Hotelo on Twinpeak Mountain and go after Aqualin",
        0x010e: "Get Aqualin",
        0x0118: "Give Aqualin to Hotelo",
        0x0122: "Talk to Tim after saving him",
        0x012c: "Tim became a Vambee/ Tim is Saved",
        0x0136: "Talk to the drunk and discover you",
        0x0140: "Wanda talks about the vambees' nest",
        0x014a: "Meet the restaurant owner at the basement",
        0x0172: "Open all blue eyes",
        0x017c: "Get the Ugly Belt",
        0x0181: "Equip the L-Belt",
        0x0186: "The owner of the restaurant says he needs the rope",
        0x0190: "Something is happening at the church at 2 am",
        0x019a: "Enter the church infested with vambees",
        0x01a4: "Exit the church infested with vambees",
        0x01ae: "The Father asks you to retrieve Church Bell",
        0x01cc: "Collected water scroll",
        0x01d1: "Interacting with the church bell (does not require talking to priest)",
        0x01d6: "Give the Church Bell to the priest",
        0x01e0: "Return the bell to the village",
	0x1077: "Chapter 4 Grillin Village",
        0x0258: "Acquire your second crest",
        0x0276: "Fix the Village Well",
        0x0280: "The mayor's wife asks you to fix the Gondola Gizmo",
        0x028a: "Carpenters inform you of the appearance of the item needed to fix the Gondola Gizmo",
        0x0294: "Deliver the Gizmo Gondola",
        0x029e: "A fire starts in the village",
        0x02a8: "Put out fire",
        0x02b2: "Mrs. Govern thanks you and tells musashi about the thieves",
        0x02bc: "Get the calendar and rock salt",
        0x02c6: "Use salt on the slug",
        0x02d0: "collect the fire scroll",
        0x02da: "Save the princess",
        0x02e4: "Rescue princess Filet and take her to the castle",
        0x02ee: "The mercenaries give you the location",
        0x02f0: "Reach the frost palace gate for the first time",
        0x02f8: "Meet Gingerelle",
        0x0302: "Melt boss door",
        0x030c: "Open and enter the big gate of the 3 eyes in the ice palace",
        0x0384: "Defeat Frost Dragon",
	0x1094: "Chapter 5/6 Grillin Village"
        0x0398: "Complete 4 chapter",
        0x03a2: "Start 5 chapter mayor says to visit shops",
        0x03ac: "Talk to a shop about the missing profits",
        0x03b6: "The princess disappeared and took the village profits with her",
        0x03c0: "go down fixed gondola",
        0x03ca: "Receive Handle 0",
        0x03d4: "Pick up Profits",
        0x03e8: "Give back the profits",
        0x03f2: "Finish the events of the second Steamwood",
        0x044c: "Get the Wind Scroll",
        0x0460: "break your own bincho field",
        0x047e: "See the mutant ant at the mountain entrance",
        0x0488: "select to take gondola to ant",
    0x1011: "Chapter 2 Upper Village", 
	0x1053: "Chapter 3 Upper Village", 
	0x1078: "Chapter 4 Upper Village", 
    0x1095: "Chapter 5/6 Upper Village"
    0x2013: "Chapter 2 Toy Shop", 
	0x2055: "Chapter 3 Toy Shop", 
	0x207a: "Chapter 4 Toy Shop", 
    0x2097: "Chapter 5/6 Toy Shop", 
    0x2015: "Chapter 2 Bakery", 
	0x2056: "Chapter 3 Bakery", 
	0x207b: "Chapter 4 Bakery", #two bosses killed
	0x2098: "Chapter 5/6 Bakery", 
    0x2016: "Chapter 2 Grocery", 
	0x2057: "Chapter 3 Grocery", 
	0x207c: "Chapter 4 Grocery",#two bosses killed
	0x2099: "Chapter 5/6 Grocery", 
    0x201a: "Chapter 2 Restaurant", 
	0x205b: "Chapter 3 Restaurant", #check if tim was saved
	0x2080: "Chapter 4 Restaurant", 
    0x209d: "Chapter 5/6 Restaurant"

