bfm_regions: dict[str, tuple[str]] = {
    "Menu": ("Grillin Village",),
    "Grillin Village": ("Somnolent Forest","Somnolent Forest Deadend","Steamwood Forest","Mine Entrance","Restaurant Basement","Upper Grillin Village"),
    "Upper Grillin Village": ("Twinpeak Entrance","Upper Mines"),
    "Somnolent Forest": ("Somnolent Forest Behind Steam","Meandering Forest","Island of Dragons"),
    "Somnolent Forest Deadend": tuple(),
    "Somnolent Forest Behind Steam": tuple(),
    "Island of Dragons": tuple(),
    "Steamwood Forest": tuple(),
    "Twinpeak Entrance": ("Twinpeak Around the Bend","Twinpeak Path to Skullpion"),
    "Twinpeak Around the Bend": ("Twinpeak Waterfall Cave 1",),
    "Twinpeak Waterfall Cave 1": ("Twinpeak Rope Bridge",),
    "Twinpeak Rope Bridge": ("Twinpeak Waterfall Cave 2",),
    "Twinpeak Waterfall Cave 2": ("Twinpeak Second Peak",),
    "Twinpeak Second Peak": tuple(),
    "Twinpeak Path to Skullpion": tuple(),
    "Mine Entrance": ("Mine Conveyor Belt Room",),
    "Mine Conveyor Belt Room": ("Misteria Underground Lake",),
    "Misteria Underground Lake": tuple(),
    "Restaurant Basement": ("Restaurant Basement Behind Pole Jumps","Restaurant Basement Dark Platform Maze 2","Restaurant Basement Planks Over Lava","Restaurant Basement Bowling 1","Restaurant Basement Near Rotating Platforms","Restaurant Basement Path to Crest Guardian"),
    "Restaurant Basement Behind Pole Jumps": tuple(),
    "Restaurant Basement Dark Platform Maze 2": ("Restaurant Basement Dark Platform Maze 3",),
    "Restaurant Basement Dark Platform Maze 3": tuple(),
    "Restaurant Basement Planks Over Lava": tuple(),
    "Restaurant Basement Bowling 1": ("Restaurant Basement Bowling 2",),
    "Restaurant Basement Bowling 2": tuple(),
    "Restaurant Basement Near Rotating Platforms": tuple(),
    "Restaurant Basement Path to Crest Guardian": tuple(),
    "Meandering Forest": ("Frozen Palace Entrance",),
    "Frozen Palace Entrance": ("Frozen Palace Red Eye Maze","Frozen Palace Crate Pile","Frozen Palace Green Eye Maze","Frozen Palace Atrium Right Balcony"),
    "Frozen Palace Red Eye Maze": ("Frozen Palace Blue Eye Door",),
    "Frozen Palace Blue Eye Door": tuple(),
    "Frozen Palace Crate Pile": tuple(),
    "Frozen Palace Green Eye Maze": tuple(),
    "Frozen Palace Atrium Right Balcony": tuple(),
    "Upper Mines": ("Upper Mines Ant Parade",),
    "Upper Mines Ant Parade": ("Upper Mines Before Digging",),
    "Upper Mines Before Digging": tuple()
}