bfm_regions: dict[str, tuple[str]] = {
    "Menu": ("Spiral Tower",),
    "Spiral Tower": ("Grillin Village",),
    "Grillin Village": ("Castle","Somnolent Forest","Somnolent Forest Deadend","Steamwood Forest","Mine Entrance","Restaurant Basement","Upper Grillin Village","Grillin Reservoir","Toy Shop Series 1","Defeat First Boss"),
    "Castle": tuple(),
    "Upper Grillin Village": ("Twinpeak Entrance","Upper Mines"),
    "Defeat First Boss": ("Defeat Second Boss",),
    "Defeat Second Boss": ("Defeat Third Boss",),
    "Defeat Third Boss": ("Defeat Fourth Boss",),
    "Defeat Fourth Boss": tuple(),
    "Somnolent Forest": ("Somnolent Forest Behind Steam","Meandering Forest","Island of Dragons"),
    "Somnolent Forest Deadend": tuple(),
    "Somnolent Forest Behind Steam": tuple(),
    "Island of Dragons": tuple(),
    "Steamwood Forest": ("Sky Island", "Steamwood 2"),
    "Steamwood 2": tuple(),
    "Sky Island": ("Soda Fountain",),
    "Soda Fountain": tuple(),
    "Twinpeak Entrance": ("Twinpeak Around the Bend","Twinpeak Path to Skullpion"),
    "Twinpeak Around the Bend": ("Twinpeak Waterfall Cave 1",),
    "Twinpeak Waterfall Cave 1": ("Twinpeak Rope Bridge",),
    "Twinpeak Rope Bridge": ("Twinpeak Waterfall Cave 2",),
    "Twinpeak Waterfall Cave 2": ("Twinpeak Second Peak",),
    "Twinpeak Second Peak": tuple(),
    "Twinpeak Path to Skullpion": ("Skullpion Arena",),
    "Skullpion Arena": tuple(),
    "Mine Entrance": ("Mine Conveyor Belt Room","Scrap Depository","Grillin Reservoir"),
    "Mine Conveyor Belt Room": ("Misteria Underground Lake",),
    "Misteria Underground Lake": tuple(),
    "Scrap Depository": tuple(),
    "Grillin Reservoir": ("Reservoir Tunnel",),
    "Reservoir Tunnel": ("Wind Scroll",),
    "Wind Scroll": tuple(),
    "Restaurant Basement": ("Restaurant Basement Behind Pole Jumps","Restaurant Basement Teleport Maze","Restaurant Basement Dark Platform Maze 2","Restaurant Basement Planks Over Lava","Restaurant Basement Bowling 1","Restaurant Basement Near Rotating Platforms","Restaurant Basement Path to Crest Guardian"),
    "Restaurant Basement Behind Pole Jumps": tuple(),
    "Restaurant Basement Teleport Maze": tuple(),
    "Restaurant Basement Dark Platform Maze 2": ("Restaurant Basement Dark Platform Maze 3",),
    "Restaurant Basement Dark Platform Maze 3": tuple(),
    "Restaurant Basement Planks Over Lava": tuple(),
    "Restaurant Basement Bowling 1": ("Restaurant Basement Bowling 2",),
    "Restaurant Basement Bowling 2": tuple(),
    "Restaurant Basement Near Rotating Platforms": tuple(),
    "Restaurant Basement Path to Crest Guardian": ("Relic Keeper Arena",),
    "Relic Keeper Arena": tuple(),
    "Meandering Forest": ("Frozen Palace Entrance","Graveyard"),
    "Graveyard": tuple(),
    "Frozen Palace Entrance": ("Frozen Palace Red Eye Door","Frozen Palace Red Eye Room","Frozen Palace Crate Pile","Frozen Palace Green Eye Maze","Frozen Palace Blue Eye Door","Frost Dragon Door"),
    "Frost Dragon Door": ("Frost Dragon Arena",),
    "Frost Dragon Arena": tuple(),
    "Frozen Palace Red Eye Door": ("Frozen Palace Red Eye Maze",),
    "Frozen Palace Red Eye Maze": ("Frozen Palace Atrium Right Balcony",),
    "Frozen Palace Red Eye Room": tuple(),
    "Frozen Palace Blue Eye Door": ("Frozen Palace Atrium Left Balcony",),
    "Frozen Palace Atrium Left Balcony": tuple(),
    "Frozen Palace Crate Pile": tuple(),
    "Frozen Palace Green Eye Maze": ("Frozen Palace Atrium Right Balcony",),
    "Frozen Palace Atrium Right Balcony": tuple(),
    "Upper Mines": ("Upper Mines Behind Poison",),
    "Upper Mines Behind Poison": ("Upper Mines Poison Elevators",),
    "Upper Mines Poison Elevators": ("Upper Mines Big Fan Room","Queen Ant Arena"),
    "Queen Ant Arena": tuple(),
    "Upper Mines Big Fan Room": ("Upper Mines Ant Parade",),
    "Upper Mines Ant Parade": ("Upper Mines Before Digging",),
    "Upper Mines Before Digging": tuple(),
    "Toy Shop Series 1": ("Toy Shop Series 2","Toy Shop Series 3","Toy Shop Series 4","Toy Shop Series 5","Toy Shop Series 6","Toy Shop Series Special"),
    "Toy Shop Series 2": tuple(),
    "Toy Shop Series 3": tuple(),
    "Toy Shop Series 4": tuple(),
    "Toy Shop Series 5": tuple(),
    "Toy Shop Series 6": tuple(),
    "Toy Shop Series Special": tuple()
}