bfm_regions: dict[str, tuple[str]] = {
    "Menu": ("Spiral Tower",),
    "Spiral Tower": ("Grillin Village",),
    "Grillin Village": ("Somnolent Forest","Somnolent Forest Deadend","Steamwood Forest","Mine Entrance","Restaurant Basement","Upper Grillin Village","Grillin Reservoir"),
    "Upper Grillin Village": ("Twinpeak Entrance","Upper Mines"),
    "Somnolent Forest": ("Somnolent Forest Behind Steam","Meandering Forest","Island of Dragons"),
    "Somnolent Forest Deadend": tuple(),
    "Somnolent Forest Behind Steam": tuple(),
    "Island of Dragons": tuple(),
    "Steamwood Forest": tuple(),
    "Twinpeak Entrance": ("Twinpeak Around the Bend","Twinpeak Path to Skullpion"),
    "Twinpeak Around the Bend": ("Twinpeak Waterfall Cave 1",),
    "Twinpeak Waterfall Cave 1": ("Twinpeak Rope Bridge",),
    "Twinpeak Rope Bridge": ("Twinpeak Waterfall Cave 2",),
    "Twinpeak Waterfall Cave 2": ("Twinpeak Second Peak",),
    "Twinpeak Second Peak": tuple(),
    "Twinpeak Path to Skullpion": ("Skullpion Arena",),
    "Skullpion Arena": tuple(),
    "Mine Entrance": ("Mine Conveyor Belt Room",),
    "Mine Conveyor Belt Room": ("Misteria Underground Lake",),
    "Misteria Underground Lake": tuple(),
    "Grillin Reservoir": ("Reservoir Tunnel",),
    "Reservoir Tunnel": ("Wind Scroll",),
    "Wind Scroll": tuple(),
    "Restaurant Basement": ("Restaurant Basement Behind Pole Jumps","Restaurant Basement Teleport Maze","Restaurant Basement Dark Platform Maze 2","Restaurant Basement Planks Over Lava","Restaurant Basement Bowling 1","Restaurant Basement Near Rotating Platforms","Restaurant Basement Path to Crest Guardian"),
    "Restaurant Basement Behind Pole Jumps": tuple(),
    "Restaurant Basement Teleport Maze": tuple(),
    "Restaurant Basement Dark Platform Maze 2": ("Restaurant Basement Dark Platform Maze 3",),
    "Restaurant Basement Dark Platform Maze 3": tuple(),
    "Restaurant Basement Planks Over Lava": tuple(),
    "Restaurant Basement Bowling 1": ("Restaurant Basement Bowling 2",),
    "Restaurant Basement Bowling 2": tuple(),
    "Restaurant Basement Near Rotating Platforms": tuple(),
    "Restaurant Basement Path to Crest Guardian": tuple(),
    "Meandering Forest": ("Frozen Palace Entrance",),
    "Frozen Palace Entrance": ("Frozen Palace Red Eye Door","Frozen Palace Red Eye Room","Frozen Palace Crate Pile","Frozen Palace Green Eye Maze","Frozen Palace Blue Eye Door","Frost Dragon Door"),
    "Frost Dragon Door": tuple(),
    "Frozen Palace Red Eye Door": ("Frozen Palace Red Eye Maze",),
    "Frozen Palace Red Eye Maze": tuple(),
    "Frozen Palace Red Eye Room": tuple(),
    "Frozen Palace Blue Eye Door": ("Frozen Palace Atrium Left Balcony",),
    "Frozen Palace Atrium Left Balcony": tuple(),
    "Frozen Palace Crate Pile": tuple(),
    "Frozen Palace Green Eye Maze": ("Frozen Palace Atrium Right Balcony",),
    "Frozen Palace Atrium Right Balcony": tuple(),
    "Upper Mines": ("Upper Mines Big Fan Room",),
    "Upper Mines Big Fan Room": ("Upper Mines Ant Parade",),
    "Upper Mines Ant Parade": ("Upper Mines Before Digging",),
    "Upper Mines Before Digging": tuple()
}